/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_homepage (void);
GtkWidget* create_window_login (void);
GtkWidget* create_window_admin (void);
GtkWidget* create_window_dashboard_member (void);
GtkWidget* create_window_dashboard_coach (void);
