/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Interface (void);
GtkWidget* create_Login (void);
GtkWidget* create_Admin (void);
GtkWidget* create_Ajouterequipement (void);
GtkWidget* create_Accueil_Membre (void);
GtkWidget* create_Modifierequipement (void);
GtkWidget* create_Ajoutercours (void);
GtkWidget* create_AjouterEntraineur (void);
GtkWidget* create_AjouterCentre (void);
GtkWidget* create_AjouterMembre (void);
GtkWidget* create_Modifiercours (void);
GtkWidget* create_ModifierEntraineur (void);
GtkWidget* create_ModifierCentre (void);
GtkWidget* create_ModifierMembre (void);
GtkWidget* create_sign_up_Membre (void);
GtkWidget* create_sign_up_Coach (void);
GtkWidget* create_Accueil_Entraineur (void);
