/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int main (int argc, char *argv[])
{
  GtkWidget *Interface;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  // ADD THESE LINES TO TELL GTK WHERE TO FIND YOUR IMAGES:
  add_pixmap_directory ("pixmaps");
  add_pixmap_directory ("../pixmaps");
  add_pixmap_directory ("./pixmaps");
  // If running from a different location, you can add absolute path:
  // add_pixmap_directory ("/full/path/to/your/project/pixmaps");

  Interface = create_Interface ();
  gtk_widget_show (Interface);

  gtk_main ();
  return 0;
}
