/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "callbacks.h"

int
main (int argc, char *argv[])
{
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);
  gtk_rc_parse("gtkrc");
  printf("Fichier de style gtkrc chargé\n");

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
  add_pixmap_directory ("./pixmaps");
  add_pixmap_directory ("./../pixmaps");
  add_pixmap_directory ("./images");

  // Charger l'image de fond
  load_background_image();

  // Créer la page d'accueil
  GtkWidget *window = create_window_homepage();
  
  if (window != NULL) {
    // Appliquer l'image de fond (cherche eventbox_bg_homepage)
    appliquer_background_a_fenetre(window);
    
    // Appliquer les couleurs aux frames
    appliquer_couleurs_tous_frames(window);
    appliquer_couleurs_sombres(window);
    gtk_widget_show_all(window);
  }

  gtk_main ();
  return 0;
}
